// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/apigatewayv2/ApiGatewayV2Client.h>
#include <aws/cloudtrail/CloudTrailClient.h>
#include <aws/elasticache/ElastiCacheClient.h>
#include <aws/ivschat/IvschatClient.h>
#include <aws/mpa/MPAClient.h>
#include <aws/rolesanywhere/RolesAnywhereClient.h>
#include <aws/sts/STSClient.h>
