// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/autoscaling-plans/AutoScalingPlansClient.h>
#include <aws/compute-optimizer/ComputeOptimizerClient.h>
#include <aws/fms/FMSClient.h>
#include <aws/lambda/LambdaClient.h>
#include <aws/opensearch/OpenSearchServiceClient.h>
#include <aws/sagemaker-edge/SagemakerEdgeManagerClient.h>
#include <aws/verifiedpermissions/VerifiedPermissionsClient.h>
