// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bcm-pricing-calculator/BCMPricingCalculatorClient.h>
#include <aws/controltower/ControlTowerClient.h>
#include <aws/geo-routes/GeoRoutesClient.h>
#include <aws/location/LocationServiceClient.h>
#include <aws/payment-cryptography-data/PaymentCryptographyDataClient.h>
#include <aws/schemas/SchemasClient.h>
#include <aws/workmail/WorkMailClient.h>
