// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/appstream/AppStreamClient.h>
#include <aws/codestar-notifications/CodeStarNotificationsClient.h>
#include <aws/eventbridge/EventBridgeClient.h>
#include <aws/kinesisanalytics/KinesisAnalyticsClient.h>
#include <aws/notifications/NotificationsClient.h>
#include <aws/s3/S3Client.h>
#include <aws/timestream-write/TimestreamWriteClient.h>
