// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bedrock-runtime/BedrockRuntimeClient.h>
#include <aws/datazone/DataZoneClient.h>
#include <aws/guardduty/GuardDutyClient.h>
#include <aws/managedblockchain/ManagedBlockchainClient.h>
#include <aws/pi/PIClient.h>
#include <aws/service-quotas/ServiceQuotasClient.h>
