// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/athena/AthenaClient.h>
#include <aws/comprehendmedical/ComprehendMedicalClient.h>
#include <aws/firehose/FirehoseClient.h>
#include <aws/lambda-core/LambdaCoreClient.h>
#include <aws/odb/OdbClient.h>
#include <aws/s3vectors/S3VectorsClient.h>
#include <aws/trustedadvisor/TrustedAdvisorClient.h>
