// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/aiops/AIOpsClient.h>
#include <aws/cloudfront-keyvaluestore/CloudFrontKeyValueStoreClient.h>
#include <aws/ec2-instance-connect/EC2InstanceConnectClient.h>
#include <aws/iotsecuretunneling/IoTSecureTunnelingClient.h>
#include <aws/mgn/MgnClient.h>
#include <aws/rekognition/RekognitionClient.h>
#include <aws/ssm-sap/SsmSapClient.h>
