// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/chime-sdk-messaging/ChimeSDKMessagingClient.h>
#include <aws/dms/DatabaseMigrationServiceClient.h>
#include <aws/interconnect/InterconnectClient.h>
#include <aws/mediapackage-vod/MediaPackageVodClient.h>
#include <aws/qconnect/QConnectClient.h>
#include <aws/snow-device-management/SnowDeviceManagementClient.h>
