// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/AWSMigrationHub/MigrationHubClient.h>
#include <aws/chime-sdk-voice/ChimeSDKVoiceClient.h>
#include <aws/docdb-elastic/DocDBElasticClient.h>
#include <aws/internetmonitor/InternetMonitorClient.h>
#include <aws/mediapackage/MediaPackageClient.h>
#include <aws/quicksight/QuickSightClient.h>
#include <aws/snowball/SnowballClient.h>
