// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bcm-dashboards/BCMDashboardsClient.h>
#include <aws/connectparticipant/ConnectParticipantClient.h>
#include <aws/geo-maps/GeoMapsClient.h>
#include <aws/license-manager/LicenseManagerClient.h>
#include <aws/partnercentral-revenue-measurement/PartnerCentralRevenueMeasurementClient.h>
#include <aws/savingsplans/SavingsPlansClient.h>
#include <aws/wisdom/ConnectWisdomServiceClient.h>
