// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bedrock-agentcore/BedrockAgentCoreClient.h>
#include <aws/dataexchange/DataExchangeClient.h>
#include <aws/greengrass/GreengrassClient.h>
#include <aws/macie2/Macie2Client.h>
#include <aws/personalize-events/PersonalizeEventsClient.h>
#include <aws/securityhub/SecurityHubClient.h>
#include <aws/workspaces/WorkSpacesClient.h>
