// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bedrock-data-automation/BedrockDataAutomationClient.h>
#include <aws/datasync/DataSyncClient.h>
#include <aws/groundstation/GroundStationClient.h>
#include <aws/managedblockchain-query/ManagedBlockchainQueryClient.h>
#include <aws/personalize/PersonalizeClient.h>
#include <aws/serverlessrepo/ServerlessApplicationRepositoryClient.h>
