// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/backup-gateway/BackupGatewayClient.h>
#include <aws/connectcampaigns/ConnectCampaignsClient.h>
#include <aws/freetier/FreeTierClient.h>
#include <aws/lexv2-models/LexModelsV2Client.h>
#include <aws/outposts/OutpostsClient.h>
#include <aws/sagemaker-runtime-http2/SageMakerRuntimeHTTP2Client.h>
#include <aws/waf/WAFClient.h>
