// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/amp/PrometheusServiceClient.h>
#include <aws/cloudfront/CloudFrontClient.h>
#include <aws/ec2/EC2Client.h>
#include <aws/iotsitewise/IoTSiteWiseClient.h>
#include <aws/mgn/model/VcenterClient.h>
#include <aws/repostspace/RepostspaceClient.h>
#include <aws/ssm/SSMClient.h>
