// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bcm-recommended-actions/BCMRecommendedActionsClient.h>
#include <aws/cost-optimization-hub/CostOptimizationHubClient.h>
#include <aws/glacier/GlacierClient.h>
#include <aws/logs/CloudWatchLogsClient.h>
#include <aws/payment-cryptography/PaymentCryptographyClient.h>
#include <aws/sdb/SimpleDBClient.h>
#include <aws/workmailmessageflow/WorkMailMessageFlowClient.h>
