// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/appintegrations/AppIntegrationsServiceClient.h>
#include <aws/codeconnections/CodeConnectionsClient.h>
#include <aws/elasticmapreduce/EMRClient.h>
#include <aws/keyspaces/KeyspacesClient.h>
#include <aws/neptune-graph/NeptuneGraphClient.h>
#include <aws/route53domains/Route53DomainsClient.h>
#include <aws/sustainability/SustainabilityClient.h>
