// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bedrock/BedrockClient.h>
#include <aws/dax/DAXClient.h>
#include <aws/health/HealthClient.h>
#include <aws/marketplace-agreement/AgreementServiceClient.h>
#include <aws/pinpoint-email/PinpointEmailClient.h>
#include <aws/servicecatalog-appregistry/AppRegistryClient.h>
