// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/bcm-data-exports/BCMDataExportsClient.h>
#include <aws/controlcatalog/ControlCatalogClient.h>
#include <aws/geo-places/GeoPlacesClient.h>
#include <aws/lightsail/LightsailClient.h>
#include <aws/partnercentral-selling/PartnerCentralSellingClient.h>
#include <aws/scheduler/SchedulerClient.h>
#include <aws/workdocs/WorkDocsClient.h>
