// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/apprunner/AppRunnerClient.h>
#include <aws/codestar-connections/CodeStarconnectionsClient.h>
#include <aws/es/ElasticsearchServiceClient.h>
#include <aws/kinesis/KinesisClient.h>
#include <aws/networkmonitor/NetworkMonitorClient.h>
#include <aws/s3-crt/S3CrtClient.h>
#include <aws/timestream-query/TimestreamQueryClient.h>
