// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/chatbot/ChatbotClient.h>
#include <aws/directconnect/DirectConnectClient.h>
#include <aws/importexport/ImportExportClient.h>
#include <aws/marketplacecommerceanalytics/MarketplaceCommerceAnalyticsClient.h>
#include <aws/pricing/PricingClient.h>
#include <aws/signer/SignerClient.h>
