// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/agent-registry/AgentRegistryClient.h>
#include <aws/cloudformation/CloudFormationClient.h>
#include <aws/ebs/EBSClient.h>
#include <aws/iotfleetwise/IoTFleetWiseClient.h>
#include <aws/meteringmarketplace/MarketplaceMeteringClient.h>
#include <aws/redshift/RedshiftClient.h>
#include <aws/ssm-quicksetup/SSMQuickSetupClient.h>
