// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/applicationcostprofiler/ApplicationCostProfilerClient.h>
#include <aws/codeguruprofiler/CodeGuruProfilerClient.h>
#include <aws/emr-serverless/EMRServerlessClient.h>
#include <aws/kinesis-video-signaling/KinesisVideoSignalingChannelsClient.h>
#include <aws/networkflowmonitor/NetworkFlowMonitorClient.h>
#include <aws/rtbfabric/RTBFabricClient.h>
#include <aws/textract/TextractClient.h>
