// Auto-generated by install_test_gen.py — do not edit manually.
// Compilation-only test: verifies every generated client header is includable.

#include <aws/core/Aws.h>
#include <aws/appconfigdata/AppConfigDataClient.h>
#include <aws/codebuild/CodeBuildClient.h>
#include <aws/elasticfilesystem/EFSClient.h>
#include <aws/kafkaconnect/KafkaConnectClient.h>
#include <aws/mturk-requester/MTurkClient.h>
#include <aws/route53-recovery-control-config/Route53RecoveryControlConfigClient.h>
#include <aws/support-app/SupportAppClient.h>
