# misc stuff I don't really understand that curl needs for configure to succeed

SET( HAVE_GLIBC_STRERROR_R 1 CACHE STRING "Result from TRY_RUN" FORCE)
SET( HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT "" CACHE STRING "Output from TRY_RUN" FORCE)
SET( HAVE_POSIX_STRERROR_R 0 CACHE STRING "Result from TRY_RUN" FORCE)
SET( HAVE_POSIX_STRERROR_R__TRYRUN_OUTPUT "" CACHE STRING "Output from TRY_RUN" FORCE)
SET( HAVE_POLL_FINE_EXITCODE 0 CACHE STRING "Blah" FORCE )
SET( OPENSSL_CRYPTO_LIBRARY crypto CACHE STRING "Blah" FORCE )
SET( OPENSSL_SSL_LIBRARY ssl CACHE STRING "Blah" FORCE )
