#!/bin/bash

IFS=$'\n' read -d '' -r -a releases < $0/pending_releases
for i in "${releases[@]}"
do
    aws sqs send-message --queue-url  "$3"  --message "{ \"release-Id\": \"$i\", \"language: CPP\", \"releaseState\":\"$1\", \"statusMessage\":\"$2\" }" 
done

