#!/bin/bash

set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
aws s3 cp s3://aws-sdk-cpp-pipeline-sdks-team/modelsSnapshot.zip modelsLatest.zip --region us-east-1
unzip modelsLatest.zip -d modelsLatest
rm modelsLatest.zip
grep -vf ./models/pending_releases ./modelsLatest/pending_releases | tee ./modelsLatest/pending_releases
grep -vf ./models/release_notes ./modelsLatest/release_notes | tee ./modelsLatest/release_notes
touch ./not_a_release
aws s3 cp not_a_release s3://aws-sdk-cpp-pipeline-sdks-team/not_a_release --region us-east-1
rm -r ./models 
cp -r ./modelsLatest ./models
zip -r modelsSnapshot.zip ./models
aws s3 cp modelsSnapshot.zip s3://aws-sdk-cpp-pipeline-sdks-team/modelsSnapshot.zip --region us-east-1
