#!/bin/bash

aws s3 cp s3://aws-sdk-cpp-pipeline-sdks-team/modelsSnapshot.zip models.zip --region us-east-1
unzip models.zip
rm models.zip
python move_release_doc_to_models.py --modelsDir="./models" --releaseDoc="$0"
rm models.zip
zip -r modelsSnapshot.zip ./models
aws s3 cp modelsSnapshot.zip s3://aws-sdk-cpp-pipeline-sdks-team/modelsSnapshot.zip --region us-east-1
