#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
aws s3 cp s3://aws-sdk-cpp-pipeline-sdks-team/modelsSnapshot.zip models.zip --region us-east-1
unzip models.zip
rm models.zip
python $DIR/move_release_doc_to_models.py --modelsDir="./models" --releaseDoc="$0"
rm models.zip
zip -r modelsSnapshot.zip ./models
aws s3 cp modelsSnapshot.zip s3://aws-sdk-cpp-pipeline-sdks-team/modelsSnapshotCpy.zip --region us-east-1
