version: 0.2
phases:
  build:
    commands:
      - echo ${Env:CODEBUILD_SOURCE_VERSION}
      - $RELEASE_ID=$(cat ${Env:RELEASE_ID_FILENAME})
      - mkdir C:\tmp
      - mkdir C:\tmp\build
      - mv * C:\tmp
      - cd C:\tmp\build
      - cmake.exe -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug -DMINIMIZE_SIZE=ON ../aws-sdk-cpp
      - msbuild.exe ALL_BUILD.vcxproj -p:Configuration=Debug -m
      - cd ..
      - Get-ChildItem aws-sdk-cpp -Exclude *tests | Where-Object Name -Like 'aws-cpp-sdk-*' | Remove-Item -Recurse -Force
      - Get-ChildItem build -Exclude bin | Remove-Item -Recurse -Force
  post_build:
    commands:
      - cd C:\tmp
      - $BUILD_JOB_NAME=${Env:CODEBUILD_BUILD_ID}.Substring(0, ${Env:CODEBUILD_BUILD_ID}.IndexOf(":"))
      - $BUILD_URL="https://${Env:AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/projects/$BUILD_JOB_NAME/build/${Env:CODEBUILD_BUILD_ID}"
      - |
        if (${Env:CODEBUILD_BUILD_SUCCEEDING} -eq 0) {
          python aws-sdk-cpp/CI/trebuchet-release-pipeline/UpdateStatus.py -s Build -e "[BUILD FAILURE](${BUILD_URL}) (${Env:CODEBUILD_BUILD_ID})" -i $RELEASE_ID -m "Step 2 of 4. Verification of Build Failed. A technician has already been notified." -b $CODEBUILD_BUILD_SUCCEEDING;
        }
artifacts:
  files:
    - "**/*"
  base-directory: C:\tmp