# Service Group Mapping for CPack Component-Based Packaging
# Maps individual AWS service libraries to logical package groups

# Function: get_service_group_component
# Maps a service name to its package group component
# Args:
#   SERVICE_NAME - The service library name (e.g., "aws-cpp-sdk-s3")
#   OUTPUT_VAR - Variable name to store the result
# Returns:
#   Sets OUTPUT_VAR to the group name (e.g., "storage")
function(get_service_group_component SERVICE_NAME OUTPUT_VAR)
    # Core services (always required)
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(core|access-management|identity-management|queues|text-to-speech|transfer)$")
        set(${OUTPUT_VAR} "core" PARENT_SCOPE)
        return()
    endif()

    # Storage services
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(s3|s3-crt|s3control|s3outposts|s3tables|s3vectors|s3-encryption)")
        set(${OUTPUT_VAR} "storage" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(glacier|backup|backup-gateway|backupsearch)")
        set(${OUTPUT_VAR} "storage" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(storagegateway|storage-gateway|fsx|elasticfilesystem)")
        set(${OUTPUT_VAR} "storage" PARENT_SCOPE)
        return()
    endif()

    # Compute services
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(ec2|ec2-instance-connect)")
        set(${OUTPUT_VAR} "compute" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(lambda|batch|lightsail)")
        set(${OUTPUT_VAR} "compute" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(elasticbeanstalk|elastic-beanstalk)")
        set(${OUTPUT_VAR} "compute" PARENT_SCOPE)
        return()
    endif()

    # Container services
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(ecs|eks|eks-auth)")
        set(${OUTPUT_VAR} "containers" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(ecr|ecr-public)")
        set(${OUTPUT_VAR} "containers" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(apprunner|app-runner)")
        set(${OUTPUT_VAR} "containers" PARENT_SCOPE)
        return()
    endif()

    # Database services
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(dynamodb|dynamodbstreams)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(rds|rds-data)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(redshift|redshift-data|redshift-serverless)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(neptune|neptune-data|neptunegraph)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(docdb|docdb-elastic)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(timestream-query|timestream-write|timestream-influxdb)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(memorydb|elasticache|dsql)")
        set(${OUTPUT_VAR} "database" PARENT_SCOPE)
        return()
    endif()

    # Networking & Content Delivery
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(vpc-lattice|route53|route53domains|route53resolver|route53profiles)")
        set(${OUTPUT_VAR} "networking" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(route53-recovery-cluster|route53-recovery-control-config|route53-recovery-readiness)")
        set(${OUTPUT_VAR} "networking" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(cloudfront|cloudfront-keyvaluestore)")
        set(${OUTPUT_VAR} "networking" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(elb|elasticloadbalancing|elasticloadbalancingv2)")
        set(${OUTPUT_VAR} "networking" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(apigateway|apigatewaymanagementapi|apigatewayv2)")
        set(${OUTPUT_VAR} "networking" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(directconnect|globalaccelerator)")
        set(${OUTPUT_VAR} "networking" PARENT_SCOPE)
        return()
    endif()

    # Messaging & Streaming
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(sqs|sns)")
        set(${OUTPUT_VAR} "messaging" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(kinesis|kinesisanalytics|kinesisanalyticsv2)")
        set(${OUTPUT_VAR} "messaging" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(kinesisvideo|kinesis-video)")
        set(${OUTPUT_VAR} "messaging" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(eventbridge|events|mq)")
        set(${OUTPUT_VAR} "messaging" PARENT_SCOPE)
        return()
    endif()

    # AI & Machine Learning
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(bedrock|bedrock-runtime|bedrock-agent|bedrock-agent-runtime)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(bedrock-agentcore|bedrock-agentcore-control|bedrock-data-automation|bedrock-data-automation-runtime)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(sagemaker|sagemaker-runtime|sagemaker-a2i-runtime|sagemaker-edge)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(sagemaker-featurestore-runtime|sagemaker-geospatial|sagemaker-metrics)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(rekognition|comprehend|comprehendmedical)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(textract|translate)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(transcribe|transcribestreaming)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(polly|lexv2-models|lexv2-runtime|lex-models|lex)")
        set(${OUTPUT_VAR} "aiml" PARENT_SCOPE)
        return()
    endif()

    # Analytics
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(athena|emr|emr-containers|emr-serverless)")
        set(${OUTPUT_VAR} "analytics" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(glue|gluedatabrew|databrew)")
        set(${OUTPUT_VAR} "analytics" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(quicksight|opensearch|opensearchserverless)")
        set(${OUTPUT_VAR} "analytics" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(elasticsearch|es)")
        set(${OUTPUT_VAR} "analytics" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(datazone|cleanrooms|cleanroomsml|entityresolution)")
        set(${OUTPUT_VAR} "analytics" PARENT_SCOPE)
        return()
    endif()

    # Security & Identity
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(iam|sts)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(cognito-identity|cognito-idp|cognito-sync)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(kms|secretsmanager|secrets-manager)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(acm|acm-pca)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(waf|waf-regional|wafv2)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(shield|guardduty)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(macie|macie2)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(inspector|inspector2|inspectorcan|inspector-scan)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(securityhub|security-lake|detective)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(verified-permissions|verifiedpermissions|accessanalyzer)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(rolesanywhere)")
        set(${OUTPUT_VAR} "security" PARENT_SCOPE)
        return()
    endif()

    # Management & Governance
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(cloudformation|cloudtrail|cloudtrail-data)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(monitoring|logs|synthetics|cloudwatch)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(config|ssm|systems-manager)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(ssm-contacts|ssm-incidents|ssm-quicksetup|ssm-sap)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(organizations|servicecatalog|servicecatalog-appregistry)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(resource-groups|resource-explorer-2)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(application-autoscaling|autoscaling|autoscaling-plans)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(opsworks|opsworkscm)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(trustedadvisor|health|healthlake)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(servicequotas|support|supportapp)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(controltower|cloudcontrol)")
        set(${OUTPUT_VAR} "management" PARENT_SCOPE)
        return()
    endif()

    # Application Integration
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(appconfig|appconfigdata)")
        set(${OUTPUT_VAR} "appintegration" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(appsync)")
        set(${OUTPUT_VAR} "appintegration" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(step-functions|sfn)")
        set(${OUTPUT_VAR} "appintegration" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(appflow|appintegrations)")
        set(${OUTPUT_VAR} "appintegration" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(scheduler|eventbridge)")
        set(${OUTPUT_VAR} "appintegration" PARENT_SCOPE)
        return()
    endif()

    # Developer Tools
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(code|xray)")
        set(${OUTPUT_VAR} "devtools" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(cloud9)")
        set(${OUTPUT_VAR} "devtools" PARENT_SCOPE)
        return()
    endif()

    # Media Services
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(media|ivs|elemental)")
        set(${OUTPUT_VAR} "media" PARENT_SCOPE)
        return()
    endif()

    # IoT
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(iot|greengrass)")
        set(${OUTPUT_VAR} "iot" PARENT_SCOPE)
        return()
    endif()

    # Business Applications
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(workspaces|workdocs|workmail|chime|connect|wisdom|voice-id)")
        set(${OUTPUT_VAR} "business" PARENT_SCOPE)
        return()
    endif()

    # Migration & Transfer
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(dms|migration|datasync|snowball|discovery)")
        set(${OUTPUT_VAR} "migration" PARENT_SCOPE)
        return()
    endif()
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(awstransfer)")
        set(${OUTPUT_VAR} "migration" PARENT_SCOPE)
        return()
    endif()

    # Cost Management
    if(SERVICE_NAME MATCHES "^aws-cpp-sdk-(ce|budgets|billing|bcm|pricing|savingsplans|marketplace|artifact)")
        set(${OUTPUT_VAR} "costmgmt" PARENT_SCOPE)
        return()
    endif()

    # Miscellaneous - catch-all for services not in other groups
    set(${OUTPUT_VAR} "misc" PARENT_SCOPE)
endfunction()
