#!/usr/bin/env python3

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

"""
Generates all_services_test.cpp (includes every generated client header)
and patches CMakeLists.txt to add the all_services_test executable.
"""

import argparse
import os
import re
from pathlib import Path
from typing import List, Optional, Set

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GENERATED_SRC = os.path.normpath(os.path.join(SCRIPT_DIR, "../../../generated/src"))
OUTPUT_CPP = os.path.join(SCRIPT_DIR, "../../CI/install-test/all_services_test.cpp")
CMAKE = os.path.join(SCRIPT_DIR, "../../CI/install-test/CMakeLists.txt")

GENERATED_BLOCK_START = "# -- all_services_test build target --"


class InstallTestGen(object):

    def __init__(self, debug: bool, **kwargs):
        self.debug = debug

    def generate(self, clients_to_build: Optional[Set[str]]):
        """Generate install tests for the given client list
        
        :param clients_to_build: Set of client names to generate tests for
        :return: 0 if success, non-zero otherwise
        """
        try:
            client_list = clients_to_build if clients_to_build else None
            headers = self._find_client_headers(client_list)
            components = [self._sdk_component(h) for h in headers]
            self._write_cpp(headers)
            self._patch_cmake(components)
            
            if self.debug:
                if client_list:
                    print(f"Generated compilation test for {len(headers)} clients: {', '.join(client_list)}")
                else:
                    print(f"Generated compilation test for all {len(headers)} clients")
            return 0
        except Exception as e:
            if self.debug:
                print(f"Error generating install tests: {e}")
            return -1

    def _find_client_headers(self, client_list: Optional[Set[str]] = None) -> List[str]:
        headers = []
        for path in Path(GENERATED_SRC).rglob("*Client.h"):
            parts = path.parts
            if "include" not in parts:
                continue
            header_path = "/".join(parts[parts.index("include") + 1:])
            if client_list:
                service_name = self._sdk_component(header_path)
                if service_name and service_name in client_list:
                    headers.append(header_path)
            else:
                headers.append(header_path)
        return sorted(headers)

    def _sdk_component(self, header: str) -> Optional[str]:
        # "aws/s3-crt/S3CrtClient.h" -> "s3-crt"
        parts = header.split("/")
        return parts[1] if len(parts) >= 3 else None

    def _write_cpp(self, headers: List[str]) -> None:
        lines = [
            "// Auto-generated by install_test_gen.py — do not edit manually.",
            "// Compilation-only test: verifies every generated client header is includable.",
            "",
            "#include <iostream>",
            "#include <aws/core/Aws.h>",
        ]
        lines += [f"#include <{h}>" for h in headers]
        lines += [
            "",
            "int main() {",
            "    Aws::SDKOptions options;",
            "    Aws::InitAPI(options);",
            "    std::cout << \"Compilation test succeeded\\n\";",
            "    Aws::ShutdownAPI(options);",
            "    return 0;",
            "}",
            ""
        ]
        with open(OUTPUT_CPP, "w") as f:
            f.write("\n".join(lines))
        if self.debug:
            print(f"Wrote {OUTPUT_CPP} ({len(headers)} headers)")

    def _patch_cmake(self, components: List[Optional[str]]) -> None:
        comp_list = " ".join(sorted(set(filter(None, components))))
        block = (
            f"{GENERATED_BLOCK_START}\n"
            f"find_package(AWSSDK REQUIRED COMPONENTS core {comp_list})\n"
            f"add_executable(all_services_test all_services_test.cpp)\n"
            f"target_link_libraries(all_services_test ${{AWSSDK_LINK_LIBRARIES}})\n"
            f"target_include_directories(all_services_test PRIVATE ${{AWSSDK_INCLUDE_DIRS}})\n"
        )
        with open(CMAKE, "r") as f:
            content = f.read()

        pattern = re.compile(
            re.escape(GENERATED_BLOCK_START) + r".*?(?=\n# |\Z)",
            re.DOTALL,
        )
        if pattern.search(content):
            content = pattern.sub(block, content)
        else:
            content = content.rstrip("\n") + "\n\n" + block + "\n"

        with open(CMAKE, "w") as f:
            f.write(content)
        if self.debug:
            print(f"Patched {CMAKE}")

def parse_arguments():
    parser = argparse.ArgumentParser(description="Generate compilation test for AWS SDK C++ clients")
    parser.add_argument("--client_list", type=str, help="Comma-separated or semi-colon-separated list of SDK clients")
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_arguments()
    client_list = None
    if args.client_list:
        client_list = args.client_list.replace(";", ",").split(",")
        client_list = [c.strip() for c in client_list if c.strip()]
    
    install_test_gen = InstallTestGen(debug=True)
    exit_code = install_test_gen.generate(client_list)
    exit(exit_code)