name: Block Merge During Daily Release
on:
  merge_group:
    types: [ checks_requested ]
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/block-merge-based-on-time@v2.1.37
        with:
          timezone: "UTC"
          after: 18:00
          before: 20:00
          base-branches: "(default)"